### ISSUE TITLE
Demo available?

### ISSUE THREAD

**Issue by y0va** [ortoloco/juntagrico-bookkeeping#1]
Ich hab diese juntagrico app(?) nicht zum laufen bekommen. Bin daran aber sehr interessiert. Könnt ihr ein paar Tips geben?

**Comment by motu55** [comment]
Hallo
Diese software ist noch im aufbau und nicht vollumfänglich benutzbar.
Bitte schreibe eine Email an info@juntagrico.org für weitere Fragen, damit wir das nicht hier in den Issues besprechen müssen.
MfG
